# Generated by Django 4.1.7 on 2023-03-20 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EVALUACION',
            fields=[
                ('COD_EVA', models.IntegerField(primary_key=True, serialize=False)),
                ('INSTITUCION', models.CharField(max_length=1)),
                ('MUNICIPIO', models.CharField(max_length=1)),
                ('DETALLE', models.CharField(max_length=1)),
                ('ESTADO', models.CharField(max_length=1)),
            ],
            options={
                'db_table': 'EVALUACION',
            },
        ),
    ]
